spring:
  application:
    name: qnow
  modulith:
    detection-strategy: explicitly-annotated
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/qnow}
    username: ${SPRING_DATASOURCE_USERNAME:qnow}
    password: ${SPRING_DATASOURCE_PASSWORD:qnow}
  flyway:
    enabled: true
    locations: classpath:db/migration/{vendor}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,modulith
